[package]
name = "pie-nix"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.17", features = ["derive"]}
clap_derive = "4.5.13"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
